# Generated by Django 4.0 on 2022-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crime_date', models.DateField()),
                ('crime_type', models.CharField(max_length=30)),
                ('crime_level', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('punishment', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'crime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('dependent_name', models.CharField(blank=True, max_length=30, null=True)),
                ('prison_name', models.CharField(max_length=30)),
                ('prison_term', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'criminal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('evidence', models.CharField(max_length=30)),
                ('section_of_law', models.CharField(max_length=10)),
                ('case_status', models.CharField(max_length=30)),
                ('lawyer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'victim',
                'managed': False,
            },
        ),
    ]
